// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDQ-Ck3q3Y7VUSpHSUEqEVSxxBo5bGzE',
    appId: '1:365782655990:web:08c70346f308f32e935dd7',
    messagingSenderId: '365782655990',
    projectId: 'notificationapp-9e96f',
    authDomain: 'notificationapp-9e96f.firebaseapp.com',
    storageBucket: 'notificationapp-9e96f.firebasestorage.app',
    measurementId: 'G-83MG0B4DQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLT_tGfyaK7UCjnUv0bUdAwO4O_TTNX1E',
    appId: '1:365782655990:android:9665a93d770ed7ff935dd7',
    messagingSenderId: '365782655990',
    projectId: 'notificationapp-9e96f',
    storageBucket: 'notificationapp-9e96f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDQ-Ck3q3Y7VUSpHSUEqEVSxxBo5bGzE',
    appId: '1:365782655990:web:9b04bcff8fca17d5935dd7',
    messagingSenderId: '365782655990',
    projectId: 'notificationapp-9e96f',
    authDomain: 'notificationapp-9e96f.firebaseapp.com',
    storageBucket: 'notificationapp-9e96f.firebasestorage.app',
    measurementId: 'G-YFQEB7RXBZ',
  );
}
